# Generated by Django 4.2.6 on 2023-10-22 20:27

import chat.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'amigo',
                'verbose_name_plural': 'amigos',
            },
        ),
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nombre de usuario')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, verbose_name='nombre de busqueda')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=chat.models.upload_image_profile, verbose_name='foto de perfil')),
                ('friends', models.ManyToManyField(related_name='friends_profiles', to='chat.friendmodel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfiles',
                'ordering': ['slug'],
            },
        ),
        migrations.AddField(
            model_name='friendmodel',
            name='friend_porfile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chat.profilemodel', verbose_name='amigo'),
        ),
    ]
